DEBUG: false
DEBUG_FREQ: 1
LOGDIR: ''
DEVICE: 'cuda'
EXP_NAME: 'token3d'
OUTPUT_DIR: 'results/'
NUM_WORKERS: 8
SEED_VALUE: -1
SAVE_FREQ: 1
DATASET:
  SEQLEN: 16
  SAMPLE_POOL: 128
  OVERLAP: 0.5
  RANDOM_SAMPLE: false
  RANDOM_START: true
  SIZE_JITTER: 0.
  ROT_JITTER: 0
  RANDOM_FLIP: 0.5
  RANDOM_CROP_P: 0.2
  RANDOM_CROP_SIZE: 0.6
  COLOR_JITTER: 0.3
  ERASE_PROB: 0.3
  ERASE_PART: 0.7
  ERASE_FILL: False
  ERASE_KP: False
  ERASE_MARGIN: 0.2
  WIDTH: 224
  HEIGHT: 224
EVAL:
  SAMPLE_POOL: 128
  SEQLEN: 16
  BATCH_SIZE: 8
  INTERPOLATION: 1
  BBOX_SCALE: 1.1
LOSS:
  KP_2D_W: 300.0
  KP_3D_W: 600.0
  SHAPE_W: 0.06
  POSE_W: 60.0
  SMPL_NORM: 1.0
  ACCL_W: 0.0
  TEMP_W: 0.0
TRAIN:
  BATCH_SIZE_3D: 4
  BATCH_SIZE_2D: 3 
  BATCH_SIZE_IMG: 7
  IMG_USE_FREQ: 1
  NUM_ITERS_PER_EPOCH: -1
  RESUME: ''
  START_EPOCH: 0
  END_EPOCH: 100   #
  DATASETS_2D:
    - 'insta'
    - 'posetrack'
    - 'pennaction'
  DATASETS_3D:
    # - '3dpw'
    - 'mpii3d'
    - 'h36m'
  DATASETS_IMG:
   - 'coco2014-all'
   - 'lspet'
   - 'mpii'
  DATASET_EVAL: 'h36m'
  EVAL_SET: 'val'
  OPTIM:
    LR: 0.0001
    WD: 0.00001
    OPTIM: 'Adam' 
    WARMUP_EPOCH: 0 
    WARMUP_FACTOR: 0.1
    MILESTONES: [60, 90]
MODEL:
  ENABLE_TEMP_MODELING: true
  ENABLE_TEMP_EMBEDDING: true
  ENCODER:
    NUM_BLOCKS: 6
    NUM_HEADS: 12
    SPA_TEMP_MODE: 'vanilla'
  MASK_RATIO: 0.
  TEMPORAL_LAYERS: 3
  TEMPORAL_NUM_HEADS: 12
  LOAD_PRETRAINED_HEAD: True
    
